### ISSUE TITLE
Should we implement anti-ASIC feature like Ethereum will?

### ISSUE THREAD

**Issue by Cupmouse** [nekonium/go-nekonium#2]
Recently the largest ASIC miner distributor **Bitmain** has annouced Ethereum ASIC miner.
At this point, Ethereum is preparing counter anti-ASIC harkfork.

I am aware that if Ethereum implemented a such feature then we, Nekonium network, will receive large portion of those power thus making GPU mining difficult and mining more centralized.

Should we implement anti-ASIC feature or not?

**Comment by uneuro** [comment]
I think we also should follow this way asap, even if theses "asic" are not so much better than actual gpu.

**Comment by Cupmouse** [comment]
Ethereum will not implement Anti-ASIC Fork as evident by Vitalik Buterin opposing this issue, and no further discussion in EIP958.

Closing this issue.
